# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Executable cycle program for a UPMEM DPU rank.

This is intentionally ordinary Python and is the calibration surface for the
backend.  An agent can change the constants or formulas after microprofiling a
real DIMM without changing the structural target.

The initial instruction model follows Gomez-Luna et al. (arXiv:2105.03814):
the fine-grained DPU pipeline prevents one tasklet from issuing more often than
once every 11 cycles and reaches peak throughput with 11 runnable tasklets;
32-bit integer addition is native, while a general 32-bit multiplication can
lower to as many as 32 ``mul_step`` instructions.  Memory constants mirror
uPIMulator commit 870d916: 8-byte minimum DMA accesses, 1 KiB wordlines, and
the default tRCD/tCL/tBL/tRAS/tRP values in ``src/main.go``.

All results are cycle counts.  There is deliberately no clock-frequency or
wall-time conversion in this abstraction.
"""

from __future__ import annotations

import math

from ...perf import cost, rule


PIPELINE_STAGES = 14
REVOLVER_CYCLES = 11
MAX_TASKLETS = 24

ADD_INSTRUCTIONS = 1
SUB_INSTRUCTIONS = 1
MUL_STEP_INSTRUCTIONS = 32
# ``sdk/syslib/div32.c`` contains 32 DIV_STEP instructions plus operand-sign,
# call, and return setup.  Forty-eight is the conservative signed normal path.
SIGNED_DIV_INSTRUCTIONS = 48
# No integer sqrt primitive/runtime exists in the checked-in SDK.  Four
# division-equivalent Newton steps are the initial analytical assumption.
INTEGER_SQRT_INSTRUCTIONS = 192
INTEGER_COMPARE_INSTRUCTIONS = 1
# A C ternary/min/max generally needs one condition-setting instruction and
# one conditional move/branch.  Calibration can replace this compiler guess.
SELECT_INSTRUCTIONS = 2
BRANCH_INSTRUCTIONS = 1
# Native one-instruction bitwise AND and arithmetic shift (spec 004 ops).
AND_INSTRUCTIONS = 1
SHIFT_INSTRUCTIONS = 1

# UPMEM has no floating-point datapath.  The SDK links compiler-rt software
# routines (sdk/syslib/addsf3.c, mulsf3.c, divsf3.c, comparesf2.c).  These are
# initial normal-input dynamic-instruction assumptions, deliberately exposed
# here for agent calibration.  The simulator's compiled assembly has roughly
# 132 instructions in addsf3, 104 in mulsf3, and 143 in divsf3 across all static
# paths; the estimates below choose representative dynamic paths and include
# called helpers such as 64-bit multiply.  SQRT is not supplied by the checked-
# in uPIMulator SDK and is modeled as software Newton iteration until a
# generated-kernel microprofile replaces the estimate.
FLOAT_ADD_INSTRUCTIONS = 96
FLOAT_SUB_INSTRUCTIONS = 98
FLOAT_MUL_INSTRUCTIONS = 128
FLOAT_DIV_INSTRUCTIONS = 256
FLOAT_SQRT_INSTRUCTIONS = 384
FLOAT_COMPARE_INSTRUCTIONS = 24

MIN_DMA_BYTES = 8
WORDLINE_BYTES = 1024
T_RCD = 32
T_RAS = 78
T_RP = 32
T_CL = 32
T_BL = 8

# uPIMulator's rank-channel defaults.  They price explicit host moves only;
# device computation remains independent across the 64 DPU instances.
HOST_READ_BYTES_PER_CYCLE = 1
HOST_WRITE_BYTES_PER_CYCLE = 3


# ------------------------------------------------------------------ #
# Physical-plan calibration (spec 003 U6). A matched UPMEM kernel lowers to
# one calibrated physical plan, so its whole stream is priced once, at the
# family anchor op, with the same analytical breakdown and per-stratum
# calibration ratio as ``UPMEMPhysicalCostModel.estimate``.
# ------------------------------------------------------------------ #

ANALYTICAL_DMA_BYTES_PER_CYCLE = 8
ANALYTICAL_DMA_CALL_CYCLES = 24
ANALYTICAL_BARRIER_CYCLES = 256
ANALYTICAL_SCHEDULER_CYCLES_PER_TASKLET = 4
ANALYTICAL_SHARED_WRAM_ACCESS_DIVISOR = 4
PIPELINE_FILL_CYCLES = 13

# Mean ``anchor.logic_cycles / raw_analytical(anchor)`` per calibration key
# over ``DEFAULT_UPMEM_CALIBRATION_EVIDENCE``, keyed exactly like
# ``upmem_physical_search._calibration_key``. A missing key is factor 1.0.
# Generated by: python /work/shared/users/phd/nz264/tmp/coder014_factors.py
PHYSICAL_CALIBRATION_FACTORS = {
    ("pointwise", "separate", 12, "contiguous", 64, 16): float.fromhex("0x1.8720b10b0e742p+0"),
    ("pointwise", "separate", 12, "contiguous", 128, 32): float.fromhex("0x1.1c3b2aa669e51p+1"),
    ("pointwise", "separate", 12, "contiguous", 256, 64): float.fromhex("0x1.3eed3389f8deep+1"),
    ("pointwise", "separate", 12, "contiguous", 1024, 256): float.fromhex("0x1.a042831cd9ecap+1"),
    ("pointwise", "fused_replicated", 12, "contiguous", 256, 32): float.fromhex("0x1.08cbfa917403fp+1"),
    ("selection_flags", "separate", 12, "contiguous", "ternary", 128, 32): float.fromhex("0x1.4205f1c158465p+0"),
    ("selection_flags", "separate", 12, "contiguous", "branchless_mask", 128, 32): float.fromhex("0x1.0a986533e11a8p+0"),
    ("selection_flags", "separate", 12, "contiguous", "conditional_zero", 128, 32): float.fromhex("0x1.b0c83bdd360bdp+0"),
    ("selection_flags", "separate", 12, "contiguous", "ternary", 64, 16): float.fromhex("0x1.d269a2217daf9p-1"),
    ("selection_flags", "separate", 12, "contiguous", "ternary", 256, 64): float.fromhex("0x1.4fa19dc242f19p+0"),
    ("selection_flags", "separate", 12, "contiguous", "ternary", 512, 128): float.fromhex("0x1.e13c2a3af4ad5p+0"),
    ("selection_flags", "separate", 12, "contiguous", "conditional_zero", 32, 8): float.fromhex("0x1.f312c945d0b43p-1"),
    ("selection_flags", "separate", 12, "contiguous", "conditional_zero", 64, 16): float.fromhex("0x1.347af6c700d89p+0"),
    ("selection_flags", "separate", 12, "contiguous", "conditional_zero", 256, 64): float.fromhex("0x1.cc6f4afc61a81p+0"),
    ("selection_flags", "separate", 12, "contiguous", "branchless_mask", 64, 16): float.fromhex("0x1.881e1b0d1180bp-1"),
    ("matrix_vector", "separate", 12, "contiguous", (1,), "shared_wram", 64, 16): float.fromhex("0x1.b3c6f53a1538cp-1"),
    ("matrix_vector", "fused_replicated", 12, "contiguous", (1,), "fused_dma_packet", 128, 16): float.fromhex("0x1.a54ddf9a896fbp-1"),
    ("matrix_vector", "separate", 12, "contiguous", (12, 192, 32), "tasklet_private_wram", 64, 16): float.fromhex("0x1.f3d983e976a67p-1"),
    ("matrix_vector", "fused_replicated", 12, "contiguous", (12, 192, 32), "fused_dma_packet", 128, 16): float.fromhex("0x1.fb71b85e64373p-1"),
    ("gemm", "fused_replicated", 12, "contiguous", "fused_dma_packet", 320, 4, 16): float.fromhex("0x1.e3e27a57c767ap-1"),
    ("gemm", "fused_replicated", 12, "contiguous", "fused_dma_packet", 576, 8, 16): float.fromhex("0x1.dd29e196172e1p-1"),
    ("gemm", "fused_replicated", 12, "contiguous", "fused_dma_packet", 1088, 16, 16): float.fromhex("0x1.de69e09081a96p-1"),
    ("gemm", "fused_replicated", 12, "contiguous", "fused_dma_packet", 1056, 32, 8): float.fromhex("0x1.e6ca5b7a7b33cp-1"),
    ("gemm", "separate", 12, "contiguous", "shared_wram", 2048, 128, 64): float.fromhex("0x1.3500d1d521b24p+0"),
}

# Matcher kernel family -> physical-model kernel kind.
UPMEM_FAMILY_KINDS = {
    "pointwise": "pointwise",
    "selection": "selection_flags",
    "matrix_vector": "matrix_vector",
    "gemm": "gemm",
}


def _ceil_div(value, divisor):
    if divisor <= 0:
        raise ValueError("cost divisor must be positive")
    return math.ceil(value / divisor)


def _metric(event, name, default=1):
    return max(0, int(event.metrics.get(name, default)))


def _tasklets(event):
    candidate = event.metrics.get("candidate", {}) or {}
    # Producers must prove that the materialized phase maps a parallel loop to
    # the carried LinearLayout image.  Keep legacy synthetic events compatible,
    # but let an explicit unmapped phase fail closed to one issuing tasklet.
    if not candidate.get("tasklet_mapping", True):
        return 1
    return max(
        1,
        min(
            MAX_TASKLETS,
            int(candidate.get("tasklet_fanout", 1)),
        ),
    )


def _is_floating(event):
    """Read the numeric kind attached by the MLIR C summarizer.

    ``numeric_kind='float'`` is the canonical metric.  The aliases make the
    cost program convenient to call from focused calibration scripts and older
    trace producers without coupling the target to an MLIR type object.
    """
    if "is_float" in event.metrics:
        return bool(event.metrics["is_float"])
    value = event.metrics.get(
        "numeric_kind",
        event.metrics.get("dtype", event.metrics.get("element_type", "int")),
    )
    text = str(value).lower()
    return text.startswith(("f", "bf")) or "float" in text


def _instructions(event, integer_per_iteration, floating_per_iteration=None):
    """Return aggregate dynamic instructions for one summarized event.

    A C/assembly summarizer may provide ``instruction_count`` (canonical) or
    ``instructions``.  Such a count already includes all loop iterations and
    takes precedence over analytical per-operation defaults.  Otherwise the
    event's loop-derived ``iterations`` metric scales the integer or software-
    floating implementation cost.
    """
    for name in (
        "instruction_count",
        "summarized_instruction_count",
        "dynamic_instructions",
        "instructions",
    ):
        if name in event.metrics:
            return max(0, int(event.metrics[name]))
    per_iteration = integer_per_iteration
    if _is_floating(event) and floating_per_iteration is not None:
        per_iteration = floating_per_iteration
    return _metric(event, "iterations") * int(per_iteration)


def _pipeline_cycles(instructions, tasklets):
    """Cycles for an aggregate DPU instruction stream.

    Work is divided over tasklets, but all tasklets issue through one shared
    pipeline.  Below 11 tasklets, the revolver issue gap limits throughput;
    at and above 11, the DPU can sustain one instruction per cycle.  Pipeline
    fill/drain is paid once per summarized stream.
    """
    instructions = max(1, int(instructions))
    active = max(1, min(int(tasklets), REVOLVER_CYCLES))
    issue_cycles = _ceil_div(instructions * REVOLVER_CYCLES, active)
    return issue_cycles + PIPELINE_STAGES - 1


def _calibration_key(candidate):
    """``upmem_physical_search._calibration_key`` rebuilt from candidate fields."""
    kind = UPMEM_FAMILY_KINDS[candidate["upmem_family"]]
    common = (
        kind,
        candidate["data_layout"],
        int(candidate["tasklets"]),
        candidate.get("ownership", "contiguous"),
    )
    dma_bytes = int(candidate["dma_bytes"])
    chunk = int(candidate["chunk"])
    if kind == "pointwise":
        return common + (dma_bytes, chunk)
    if kind == "selection_flags":
        return common + (
            candidate.get("predicate_lowering", "not_applicable"),
            dma_bytes,
            chunk,
        )
    if kind == "matrix_vector":
        geometry = dict(candidate["upmem_geometry"])
        batches = int(geometry.get("batches", 1))
        batch_shape = (batches,)
        if batches > 1:
            batch_shape += (batches * int(geometry["rows"]), int(geometry["columns"]))
        return common + (batch_shape, candidate["wram_residency"], dma_bytes, chunk)
    nc, kc = int(candidate.get("nc", 0)), int(candidate.get("kc", 0))
    return common + (
        candidate["wram_residency"],
        dma_bytes,
        nc or None,
        kc or None,
    )


def _physical_kernel_cycles(candidate):
    """Calibrated logic cycles of one family-plan kernel stream on one DPU.

    Mirrors ``UPMEMPhysicalCostModel.estimate``: the analytical breakdown of
    ``candidate["upmem_features"]``, scaled per component by the stratum
    factor with largest-remainder rounding to ``round(sum)``.
    """
    features = dict(candidate["upmem_features"])
    tasklets = int(candidate["tasklets"])
    lanes = min(tasklets, REVOLVER_CYCLES)
    run = (
        _ceil_div(features["dynamic_instructions"] * REVOLVER_CYCLES, lanes)
        + PIPELINE_FILL_CYCLES
    )
    dma = _ceil_div(
        features["mram_read_bytes"] + features["mram_write_bytes"],
        ANALYTICAL_DMA_BYTES_PER_CYCLE,
    ) + ANALYTICAL_DMA_CALL_CYCLES * (
        features["mram_read_calls"] + features["mram_write_calls"]
    )
    etc = (
        ANALYTICAL_BARRIER_CYCLES * features["barrier_count"]
        + ANALYTICAL_SCHEDULER_CYCLES_PER_TASKLET * tasklets
    )
    backpressure = _ceil_div(
        features["backpressure_proxy_units"], ANALYTICAL_DMA_BYTES_PER_CYCLE
    ) + _ceil_div(
        features["shared_wram_accesses"], ANALYTICAL_SHARED_WRAM_ACCESS_DIVISOR
    )
    factor = PHYSICAL_CALIBRATION_FACTORS.get(_calibration_key(candidate), 1.0)
    scaled = [component * factor for component in (run, dma, etc, backpressure)]
    floors = [math.floor(value) for value in scaled]
    target = round(sum(scaled))
    order = sorted(
        range(len(scaled)), key=lambda index: (-(scaled[index] - floors[index]), index)
    )
    for index in order[: target - sum(floors)]:
        floors[index] += 1
    return sum(floors)


@cost(target="upmem")
def upmem_cost(target):
    """Interpret UPMEM C-level primitives over target-declared resources."""
    # Tasklet throughput is driven by the structurally mapped fanout supplied
    # in candidate.tasklet_fanout, never by the raw candidate count alone.
    rank = target.unit("rank")
    dpu = target.unit("dpu")
    tasklet = target.unit("tasklet")
    host = target.unit("host")

    def family_event(event, ctx):
        """Price a family-plan kernel once per stream, at its anchor op.

        Other events of the stream are part of the kernel the anchor already
        priced and get a zero-latency step. Without ``upmem_family`` the
        per-op scalar rules run unchanged.
        """
        candidate = event.metrics.get("candidate", {}) or {}
        # A host-placed family (spec 004 D1) runs on the host: 0 DPU cycles.
        if candidate.get("upmem_placement") == "host":
            ctx.step(latency=0, name="host_group")
            return True
        # A family the physical model does not cover (reduction) carries no
        # features and keeps the per-op rules.
        if candidate.get("upmem_features") is None:
            return False
        if event.primitive.name == candidate["upmem_anchor_op"]:
            latency = _physical_kernel_cycles(candidate)
            ctx.step(
                latency=latency,
                occupy=[
                    ctx.use(event.primitive, cycles=latency),
                    ctx.use(dpu, cycles=latency),
                    ctx.use(tasklet, cycles=latency),
                    ctx.use(target.mram, cycles=latency),
                    ctx.use(target.wram, cycles=latency),
                ],
                name=f"{candidate['upmem_family']}_kernel",
            )
        else:
            ctx.step(latency=0, name="in_kernel")
        return True

    def compute(event, ctx, instructions, name):
        latency = _pipeline_cycles(instructions, _tasklets(event))
        ctx.step(
            latency=latency,
            occupy=[
                ctx.use(event.primitive, cycles=latency),
                ctx.use(dpu, cycles=latency),
                ctx.use(tasklet, cycles=latency),
            ],
            name=name,
        )

    @rule(target.op("ADD"))
    def add(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, ADD_INSTRUCTIONS, FLOAT_ADD_INSTRUCTIONS),
            "add",
        )

    @rule(target.op("SUB"))
    def subtract(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, SUB_INSTRUCTIONS, FLOAT_SUB_INSTRUCTIONS),
            "sub",
        )

    @rule(target.op("MUL"))
    def multiply(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, MUL_STEP_INSTRUCTIONS, FLOAT_MUL_INSTRUCTIONS),
            "mul_steps",
        )

    @rule(target.op("DIV"))
    def divide(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, SIGNED_DIV_INSTRUCTIONS, FLOAT_DIV_INSTRUCTIONS),
            "divide",
        )

    @rule(target.op("SQRT"))
    def square_root(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, INTEGER_SQRT_INSTRUCTIONS, FLOAT_SQRT_INSTRUCTIONS),
            "sqrt",
        )

    @rule(target.op("CMP"))
    def compare(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(
                event, INTEGER_COMPARE_INSTRUCTIONS, FLOAT_COMPARE_INSTRUCTIONS
            ),
            "compare",
        )

    @rule(target.op("SELECT"))
    def select(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, SELECT_INSTRUCTIONS, SELECT_INSTRUCTIONS),
            "select",
        )

    def minmax(event, ctx, name):
        compare_instructions = (
            FLOAT_COMPARE_INSTRUCTIONS
            if _is_floating(event)
            else INTEGER_COMPARE_INSTRUCTIONS
        )
        compute(
            event,
            ctx,
            _instructions(
                event,
                INTEGER_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
                compare_instructions + SELECT_INSTRUCTIONS,
            ),
            name,
        )

    @rule(target.op("MIN"))
    def minimum(event, ctx):
        if family_event(event, ctx):
            return
        minmax(event, ctx, "min")

    @rule(target.op("MAX"))
    def maximum(event, ctx):
        if family_event(event, ctx):
            return
        minmax(event, ctx, "max")

    @rule(target.op("BRANCH"))
    def branch(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, BRANCH_INSTRUCTIONS, BRANCH_INSTRUCTIONS),
            "branch",
        )

    @rule(target.op("AXPBY"))
    def axpby(event, ctx):
        if family_event(event, ctx):
            return
        # Two scalar multiplies and one add per element.
        compute(
            event,
            ctx,
            _instructions(
                event,
                2 * MUL_STEP_INSTRUCTIONS + ADD_INSTRUCTIONS,
                2 * FLOAT_MUL_INSTRUCTIONS + FLOAT_ADD_INSTRUCTIONS,
            ),
            "axpby",
        )

    @rule(target.op("SCALE"))
    def scale(event, ctx):
        if family_event(event, ctx):
            return
        compute(
            event,
            ctx,
            _instructions(event, MUL_STEP_INSTRUCTIONS, FLOAT_MUL_INSTRUCTIONS),
            "scale",
        )

    # Spec 004 irregular-kernel ops. Only non-family uses reach these.
    for op_name, integer, floating in (
        ("INC", ADD_INSTRUCTIONS, FLOAT_ADD_INSTRUCTIONS),
        ("SCATTER_ADD", ADD_INSTRUCTIONS, FLOAT_ADD_INSTRUCTIONS),
        ("COMPACT", ADD_INSTRUCTIONS, ADD_INSTRUCTIONS),
        (
            "SQDIST_ACC",
            SUB_INSTRUCTIONS + MUL_STEP_INSTRUCTIONS + ADD_INSTRUCTIONS,
            FLOAT_SUB_INSTRUCTIONS + FLOAT_MUL_INSTRUCTIONS + FLOAT_ADD_INSTRUCTIONS,
        ),
        (
            "GRAD_LINEAR",
            2 * MUL_STEP_INSTRUCTIONS + SHIFT_INSTRUCTIONS + ADD_INSTRUCTIONS,
            2 * FLOAT_MUL_INSTRUCTIONS + FLOAT_ADD_INSTRUCTIONS,
        ),
        (
            "GRAD_LOGISTIC",
            2 * MUL_STEP_INSTRUCTIONS + SUB_INSTRUCTIONS + ADD_INSTRUCTIONS,
            2 * FLOAT_MUL_INSTRUCTIONS + FLOAT_SUB_INSTRUCTIONS + FLOAT_ADD_INSTRUCTIONS,
        ),
        (
            "MIN_SEL",
            INTEGER_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
            FLOAT_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
        ),
        (
            "ARGMIN_IDX",
            INTEGER_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
            FLOAT_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
        ),
        (
            "SELECT_ODD",
            AND_INSTRUCTIONS + INTEGER_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
            AND_INSTRUCTIONS + INTEGER_COMPARE_INSTRUCTIONS + SELECT_INSTRUCTIONS,
        ),
    ):

        @rule(target.op(op_name))
        def irregular(event, ctx, _name=op_name, _int=integer, _float=floating):
            if family_event(event, ctx):
                return
            compute(event, ctx, _instructions(event, _int, _float), _name.lower())

    @rule(target.op("MAC"))
    def mac(event, ctx):
        if family_event(event, ctx):
            return
        # UPMEM has no fused integer MAC.  One scalar source-level MAC is a
        # worst-case 32-step multiply followed by one native addition.
        scalar_instructions = MUL_STEP_INSTRUCTIONS + ADD_INSTRUCTIONS
        float_scalar_instructions = FLOAT_MUL_INSTRUCTIONS + FLOAT_ADD_INSTRUCTIONS
        compute(
            event,
            ctx,
            _instructions(event, scalar_instructions, float_scalar_instructions),
            "mul_add",
        )

    def dma_cycles(event, *, write):
        nbytes = max(MIN_DMA_BYTES, _metric(event, "bytes", MIN_DMA_BYTES))
        chunks = _ceil_div(nbytes, MIN_DMA_BYTES)
        wordlines = _ceil_div(nbytes, WORDLINE_BYTES)
        # First command opens a row; subsequent minimum-size bursts stream.
        # A write must also satisfy tRAS before precharge.
        row = max(T_RAS, T_RCD + T_CL + T_BL) if write else T_RCD + T_CL + T_BL
        return wordlines * (row + T_RP) + max(0, chunks - wordlines) * T_BL

    def device_dma(event, ctx, *, write, name):
        latency = dma_cycles(event, write=write)
        ctx.step(
            latency=latency,
            occupy=[
                ctx.use(event.primitive, cycles=latency),
                ctx.use(dpu, cycles=latency),
                ctx.use(target.mram, cycles=latency),
                ctx.use(target.wram, cycles=latency),
            ],
            name=name,
        )

    @rule(target.move("LD_MRAM"))
    def load_mram(event, ctx):
        if family_event(event, ctx):
            return
        device_dma(event, ctx, write=False, name="mram_to_wram")

    @rule(target.move("ST_MRAM"))
    def store_mram(event, ctx):
        if family_event(event, ctx):
            return
        device_dma(event, ctx, write=True, name="wram_to_mram")

    # WRAM operands become register loads/stores in compiled C.  Keep these
    # rules explicit so a future matcher placement can price them without
    # smuggling timing into the target.
    for move_name in ("LD_WRAM", "ST_WRAM"):

        @rule(target.move(move_name))
        def wram_register_move(event, ctx, _name=move_name):
            if family_event(event, ctx):
                return
            compute(
                event,
                ctx,
                _instructions(event, 1, 1),
                _name.lower(),
            )

    def host_transfer(event, ctx, *, to_dpu):
        nbytes = _metric(event, "bytes", 0)
        bandwidth = HOST_WRITE_BYTES_PER_CYCLE if to_dpu else HOST_READ_BYTES_PER_CYCLE
        # A rank fans a scatter/broadcast/gather across its DPU endpoints.
        # The shared rank channel is the limiting resource; individual DPU
        # work begins only after this explicit transfer activity completes.
        latency = max(1, _ceil_div(nbytes, bandwidth))
        ctx.step(
            latency=latency,
            occupy=[
                ctx.use(event.primitive, cycles=latency),
                ctx.use(host, cycles=latency),
                ctx.use(rank, cycles=latency),
            ],
            name=event.primitive.name.lower(),
        )

    @rule(target.move("SCATTER_MRAM"))
    def scatter(event, ctx):
        host_transfer(event, ctx, to_dpu=True)

    @rule(target.move("BCAST_MRAM"))
    def broadcast(event, ctx):
        # The SDK rank-broadcast primitive replicates one host transfer across
        # the selected DPUs; it is not 64 independent host payloads.
        host_transfer(event, ctx, to_dpu=True)

    @rule(target.move("GATHER_MRAM"))
    def gather(event, ctx):
        host_transfer(event, ctx, to_dpu=False)
