"""GSI APU v2 / G2 codegen — emits a G2Gtml C++ program from a DSL spec.

The g2_l1_sim Docker image (`gsi-g2-l1sim`) ships a pre-built GTML tree at
`/home/g2/gtml/` with an `example-gtml/example_tensor_add.cc` target. Our
codegen emits an equivalent `.cc` file, mounts it over the container's copy,
rebuilds only that target, and runs the resulting binary.

Public API:

    gen_apu_v2_cc(dst_path, op, shape, inputs, output)
        -> writes a valid G2Gtml C++ source at dst_path.

    build_and_run_apu_v2(cc_path, image="gsi-g2-l1sim")
        -> mounts cc_path over the container's example_tensor_add.cc, rebuilds
           and runs, returns the binary's stdout (look for "PASSED").
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path


# ----------------------------------------------------------------------------
# codegen
# ----------------------------------------------------------------------------

_GTML_BINOP = {
    "add": "add",
    "sub": "sub",
    "mul": "mul",
}


def gen_apu_v2_cc(dst_path: str, op: str,
                  num_vecs: int = 4, bits: int = 16) -> str:
    """Emit a single-file GTML program for elementwise `c = a <op> b`.

    Uses VectorPack with NUM_GRPS=1 (4096 elements per vector). Matches the
    shape and conventions of example-gtml/example_tensor_add.cc so the
    existing CMake target builds it unchanged.
    """
    gtml_fn = _GTML_BINOP[op]
    dst = Path(dst_path)
    dst.parent.mkdir(parents=True, exist_ok=True)
    src = f"""// DSL-emitted G2Gtml program — op = {op}
// Generated by allo.pim.runtime.apu_v2_codegen.

#include <iostream>
#include <cstdlib>
#include <g2_gtml.h>
#include <g2_gtml_ref.h>

static constexpr uint32_t NUM_GRPS = 1;

static void init_gtml() {{
    uint32_t l1 = GTML_SIM_MEM_LOC;
    gsi::L1Container temp(l1, 128);
    gsi::L1Container idx(l1 + 128, 16);
    gsi::gtml::G2Gtml::getInstance(temp, idx);
}}

int main() {{
    init_gtml();
    auto &gtml = gsi::gtml::G2Gtml::getInstance();
    gtml_ref::GtmlRef ref;

    constexpr uint32_t NUM_VECS = {num_vecs};
    constexpr uint32_t BITS     = {bits};
    constexpr uint32_t STRIDE   = {bits};

    gsi::VectorPack a(NUM_VECS, STRIDE, gsi::G2_TYPES::INT, BITS, 1100);
    gsi::VectorPack b(NUM_VECS, STRIDE, gsi::G2_TYPES::INT, BITS, 1300);
    gsi::VectorPack c(NUM_VECS, STRIDE, gsi::G2_TYPES::INT, BITS, 1500);

    gtml_ref::VectorPackRef a_ref(a, NUM_GRPS);
    gtml_ref::VectorPackRef b_ref(b, NUM_GRPS);
    gtml_ref::VectorPackRef c_ref(c, NUM_GRPS);

    for (uint32_t v = 0; v < NUM_VECS; v++)
        for (int e = 0; e < GTML_ELEMENTS_PER_GRP; e++) {{
            a_ref.ivecs[0][v][e] = (int16_t)(v * 10 + (e % 100));
            b_ref.ivecs[0][v][e] = (int16_t)(v * 5  + (e % 50));
        }}

    ref.copy_to_l1(a_ref);
    ref.copy_to_l1(b_ref);

    int rc = gtml.{gtml_fn}(a, b, c);
    if (rc != 0) {{
        std::cerr << "ERROR: gtml.{gtml_fn}() returned " << rc << std::endl;
        return 1;
    }}

    ref.copy_from_l1(c_ref);

    std::cout << "DSL-emitted: c = a {op} b" << std::endl;
    std::cout << "Tensor shape: " << NUM_VECS << " vectors x 4096 int" << BITS << std::endl;

    bool pass = true;
    for (uint32_t v = 0; v < NUM_VECS && pass; v++) {{
        for (int e = 0; e < GTML_ELEMENTS_PER_GRP; e++) {{
            int64_t av = a_ref.ivecs[0][v][e];
            int64_t bv = b_ref.ivecs[0][v][e];
            int64_t cv = c_ref.ivecs[0][v][e];
            int64_t expected = (int16_t)({"av + bv" if op == "add" else "av * bv" if op == "mul" else "av - bv"});
            if (cv != expected) {{
                std::cout << "FAIL at v=" << v << " e=" << e
                          << ": got " << cv << " expected " << expected << std::endl;
                pass = false;
                break;
            }}
        }}
    }}
    if (pass) {{ std::cout << "PASSED" << std::endl; return 0; }}
    else      {{ std::cout << "FAILED" << std::endl; return 1; }}
}}
"""
    dst.write_text(src)
    return str(dst)


# ----------------------------------------------------------------------------
# build + run in container
# ----------------------------------------------------------------------------

def build_and_run_apu_v2(cc_path: str, image: str = "gsi-g2-l1sim",
                         timeout_s: int = 300) -> dict:
    """Mount the DSL-emitted cc over the container's example_tensor_add.cc,
    rebuild that single target, and run the resulting binary. Returns
    dict(stage, returncode, stdout, stderr)."""
    cc_abs = os.path.abspath(cc_path)
    if not os.path.isfile(cc_abs):
        return {"stage": "pre", "returncode": -1,
                "stderr": f"no such file: {cc_abs}"}

    # Mount the emitted file over the target inside the container, rebuild,
    # then run. One docker invocation to keep the build cache hot.
    sh = (
        "cmake --build --preset l1_sim --target example_tensor_add "
        "-j$(nproc) && ./build/l1_sim/bin/example_tensor_add"
    )
    r = subprocess.run(
        [
            "docker", "run", "--rm",
            "-v", f"{cc_abs}:/home/g2/gtml/example-gtml/example_tensor_add.cc:ro",
            image, "bash", "-c", sh,
        ],
        capture_output=True, text=True, timeout=timeout_s)
    return {"stage": "run", "returncode": r.returncode,
            "stdout": r.stdout, "stderr": r.stderr}
